Add workflows for updating d:l:p

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -10,7 +10,7 @@ on:
       image:
         description: Image to run on
         type: string
-        default: registry.opensuse.org/home/tinita/branches/opensuse/templates/images/tumbleweed/containers/opensuse/example
+        default: registry.opensuse.org/home/tinita/cpanspec/container/containers/opensuse/autoupdate-perl
       repo:
         description: Repo for cpanspec
         type: string
@@ -18,14 +18,21 @@ on:
       branch:
         description: cpanspec branch
         type: string
-        default: update-perl-gh
+        default: normalize-versions
+      obs_project:
+        description: Target project in OBS
+        type: string
+        default: devel:languages:perl:autoupdate
+      cpanspec_flags:
+        description: Additional flags for cpanspec
+        type: string
+        default: --dlp
 
 jobs:
 
   update:
     runs-on: ubuntu-latest
     container:
-      #image: registry.opensuse.org/opensuse/leap:15.5
       image: ${{ inputs.image }}
 
     steps:
@@ -34,3 +41,58 @@ jobs:
         git config --global --add safe.directory '*'
 
     - uses: actions/checkout@v4
+
+    - run: |
+        git clone ${{ inputs.repo }} -b ${{ inputs.branch }}
+
+    - name: configure osc
+      env:
+        OSC_USER: ${{ secrets.OSC_USER }}
+        OSC_PASSWORD: ${{ secrets.OSC_PASSWORD }}
+      run: |
+        cp etc/oscrc ~/.oscrc
+        perl -pi -wE's/OSC_USER/$ENV{OSC_USER}/' ~/.oscrc
+        perl -pi -wE's/OSC_PASSWORD/$ENV{OSC_PASSWORD}/' ~/.oscrc
+
+    - name: fetch cpan releases
+      run: |
+        bin/fetch-cpan.sh
+        ls -lrt ~/obs-mirror
+        ls -lrt ~/obs-mirror/cpan
+
+    - name: status
+      run: |
+        ./bin/status-perl --data ~/obs-mirror --project ${{ inputs.obs_project }} --update
+        grep $'\t''todo' ~/obs-mirror/status/*.tsv || true
+
+    - name: update
+      run: |
+        ./bin/update-perl \
+            --cpanspec "$PWD/cpanspec/cpanspec" \
+            --data ~/obs-mirror \
+            --project "${{ inputs.obs_project }}" \
+            --max "${{ inputs.max_modules }}" \
+            --cpanspec-flags " ${{ inputs.cpanspec_flags }}"
+
+    - name: check
+      run: |
+        if ! grep $'\t''error' ~/obs-mirror/status/*; then
+            echo "Updates successful"
+        else
+            echo "Some updates failed!"; false
+        fi
+        ls -lrt ~/obs-mirror
+        ls -lrt ~/obs-mirror/status
+
+    - uses: actions/upload-artifact@v4
+      if: ${{ always() }}
+      with:
+        name: obs-mirror
+        path: |
+          ~/obs-mirror/cpan/
+          ~/obs-mirror/status/
+          ~/obs-mirror/auto.xml
+          ~/obs-mirror/perl.xml
+
+# Trigger with gh cli:
+# gh workflow run run.yaml [--ref branch] -f image=registry.opensuse.org/home/tinita/cpanspec/container/containers/opensuse/autoupdate-perl -f repo=https://github.com/perlpunk/cpanspec -f branch=normalize-versions -f obs_project=devel:languages:perl:autoupdate -f max_modules=1
