WIP

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -87,7 +87,11 @@ jobs:
       run: |
         ls -lrt ~/obs-mirror
         ls -lrt ~/obs-mirror/cpan
-        grep $'\t''error' ~/obs-mirror/status/*.tsv && false
+        if ! grep $'\t''error' status/*; then
+            echo "Updates successful"
+        else
+            echo "Some updates failed!"; false
+        fi
 
     - uses: actions/upload-artifact@v4
       if: ${{ always() }}
